# Each joint motor has a float32 array with their feedback values
# Each array has 3 values in this order: [position, velocity, load]
float32[] left_leg_ankle_fb
float32[] left_leg_knee_fb
float32[] left_leg_hip_roll_fb
float32[] left_leg_hip_pitch_fb
float32[] left_leg_hip_yaw_fb
float32[] right_leg_ankle_fb
float32[] right_leg_knee_fb
float32[] right_leg_hip_roll_fb
float32[] right_leg_hip_pitch_fb
float32[] right_leg_hip_yaw_fb
float32[] torso_roll_fb
float32[] torso_yaw_fb
float32[] left_arm_elbow_fb
float32[] right_arm_elbow_fb
float32[] left_arm_shoulder_fb
float32[] right_arm_shoulder_fb